(function(x='input[type="file"]:not(.enhanced)'){const b={en:{wildcard:{"image/*":"Images","audio/*":"Audio files","video/*":"Video files","text/*":"Text files","application/*":"Documents"},ui:{instruction:"Drop, browse, or paste file(s) here.",supports_any:"Supports any file.",file_type:"File type: "}},"zh-tw":{wildcard:{"image/*":"\u5716\u7247\u6A94","audio/*":"\u5F71\u97F3\u6A94","video/*":"\u5F71\u7247\u6A94","text/*":"\u6587\u5B57\u6A94","application/*":"\u6587\u4EF6"},ui:{instruction:"\u5C07\u6A94\u6848\u62D6\u66F3\u6216\u8CBC\u4E0A\u65BC\u6B64\uFF0C\u6216\u9EDE\u64CA\u958B\u555F\u8CC7\u6599\u593E\u3002",supports_any:"\u4EFB\u4F55\u6A94\u6848",file_type:"\u652F\u63F4\u683C\u5F0F\uFF1A"}}}[window.globalVar("docLang")],L=25,g=(e,s)=>{if(!s)return!0;const p=s.split(",").map(l=>l.trim().toLowerCase()),a=(e.type||"").toLowerCase(),r=(e.name||"").toLowerCase(),f=r.includes(".")?"."+r.split(".").pop():"";return p.some(l=>l.startsWith(".")?f===l:l.endsWith("/*")?a?a.startsWith(l.slice(0,-1)):!1:a?a===l:f&&p.includes(f))},C=e=>e?!(e.type===""&&e.size===0&&!e.name.includes(".")||e.type===""&&e.size%4096===0&&!e.name.includes(".")):!1,y=e=>`${e.name}_${e.size}_${e.lastModified}`,v=e=>(e._uid||(e._uid=Math.random().toString(36).substring(2,9)+"_"+Date.now()),e._uid),q=e=>{if(!e)return"0 B";const s=Math.floor(Math.log(e)/Math.log(1024));return`${(e/1024**s).toFixed(1)} ${["B","KB","MB","GB"][s]}`},S=e=>{if(!e)return"Supports any format.";const s=e.split(",").map(p=>{const a=p.trim().toLowerCase();if(b.wildcard[a])return b.wildcard[a];if(a.startsWith("."))return a.slice(1).toUpperCase();if(a.includes("/")){const[r,f]=a.split("/");return f==="*"?`${r.charAt(0).toUpperCase()+r.slice(1)} files`:f.toUpperCase()}return a});return[...new Set(s)].join(", ")},h=e=>{const s=(e.type||"").toLowerCase(),p=(e.name||"").toLowerCase(),a=p.includes(".")?p.split(".").pop():"";return s.startsWith("image/")?"image":s.startsWith("audio/")?"audio_file":s.startsWith("video/")?"video_file":s==="application/pdf"||a==="pdf"?"picture_as_pdf":["doc","docx","rtf","odt"].includes(a)||s.includes("word")?"description":["xls","xlsx","csv","ods"].includes(a)||s.includes("spreadsheet")||s.includes("csv")?"table_chart":["ppt","pptx","key"].includes(a)||s.includes("presentation")?"transition_chop":["zip","rar","7z","tar","gz","bz2"].includes(a)||s.includes("zip")||s.includes("compressed")?"folder_zip":["js","ts","jsx","tsx","html","css","scss","json","py","php","java","cpp","rs","go","sql","sh","yaml","xml"].includes(a)||s.includes("javascript")||s.includes("json")?"code":["exe","msi","dmg","iso","bin"].includes(a)?"terminal_2":"draft"};document.querySelectorAll(x).forEach(e=>{e.classList.add("enhanced");const s=e.getAttribute("accept")||"",p=S(s),a=e.hasAttribute("multiple"),r=document.createElement("div"),f=e.dataset.wrapperClass?e.dataset.wrapperClass.split(";").map(t=>t.trim()).filter(Boolean):[];r.classList.add("dropzone",...f),r.tabIndex=0,e.id&&(r.id=e.id+"-wrapper"),r.innerHTML=`
      <div class="dropzone-prompt">
        <icon-mat class="material-symbols-rounded">upload_file</icon-mat>
        <p class="dropzone-title">${b.ui.instruction}</p>
        <p class="dropzone-subtext">${b.ui.file_type}${p}</p>
      </div>
      <div class="file-preview">
        <ul class="file-list"></ul>
      </div>
    `,e.parentNode.insertBefore(r,e),r.appendChild(e);const l=r.querySelector(".file-list");let $=[],o=[],z=!1;const R=t=>t.length!==o.length?!1:t.every((n,c)=>y(n)===y(o[c])),A=()=>{z=!0;const t=new DataTransfer;o.forEach(n=>t.items.add(n)),e.files=t.files,z=!1},E=t=>{o=t,A(),e.dispatchEvent(new Event("change",{bubbles:!0})),F()};e.clearFiles=()=>{(o.length>0||e.files?.length>0)&&E([])};const F=()=>{if($.forEach(n=>URL.revokeObjectURL(n)),$=[],l.innerHTML="",!o.length){r.classList.remove("has-file");return}r.classList.add("has-file");const t=o.length<=L;o.forEach((n,c)=>{const d=document.createElement("li");d.className="file-item",d.dataset.index=c,d.dataset.key=v(n);let i="";if(t&&n.type.startsWith("image/")){const _=URL.createObjectURL(n);$.push(_),i=`<img src="${_}" class="preview-thumb" alt="Preview"/>`}else i=`<div class="preview-thumb"><span class="material-symbols-rounded" aria-hidden="true">${h(n)}</span></div>`;const u=a&&o.length>1?`
                      <button type="button" class="btn btn-secondary btn-move-up" aria-label="move up" data-balloon-pos="up" ${c===0?"disabled":""}>
                        <icon-mat class="material-symbols-rounded">keyboard_arrow_up</icon-mat>
                      </button>
                      <button type="button" class="btn btn-secondary btn-move-down" aria-label="move down" data-balloon-pos="up" ${c===o.length-1?"disabled":""}>
                        <icon-mat class="material-symbols-rounded">keyboard_arrow_down</icon-mat>
                      </button>
                    `:"";d.innerHTML=`
          ${i}
          <div class="file-details">
            <p class="file-name" title="${n.name}">${n.name||"Pasted File"}</p>
            <p class="file-size">${q(n.size)}</p>
          </div>
          <div class="display-flex input-group-horizontal" style="width: auto; font-size: 0.75rem">
            ${u}
            <button type="button" class="btn btn-danger remove-btn" aria-label="remove" data-balloon-pos="up">
                <icon-mat class="material-symbols-rounded">delete</icon-mat>
            </button>
          </div>
        `,l.appendChild(d)})},T=(t,n)=>{if(t<0||t>=o.length||n<0||n>=o.length)return;const c=Array.from(l.children),d=new Map;c.forEach(w=>{d.set(w.dataset.key,w.getBoundingClientRect())});const i=[...o],[u]=i.splice(t,1);i.splice(n,0,u),E(i),Array.from(l.children).forEach(w=>{const D=d.get(w.dataset.key);if(D){const j=w.getBoundingClientRect(),H=D.top-j.top;H!==0&&w.animate([{transform:`translateY(${H}px)`},{transform:"translateY(0)"}],{duration:250,easing:"cubic-bezier(0.2, 0, 0, 1)"})}});const U=n<t?".btn-move-up":".btn-move-down",M=l.querySelector(`[data-index="${n}"]`)?.querySelector(U);M&&!M.disabled&&M.focus()};l.addEventListener("click",t=>{const n=t.target.closest(".remove-btn"),c=t.target.closest(".btn-move-up"),d=t.target.closest(".btn-move-down");if(n){t.stopPropagation();const i=n.closest(".file-item"),u=parseInt(i.dataset.index,10);isNaN(u)||E(o.filter((_,U)=>U!==u));return}if(c){t.stopPropagation();const i=c.closest(".file-item"),u=parseInt(i.dataset.index,10);isNaN(u)||T(u,u-1);return}if(d){t.stopPropagation();const i=d.closest(".file-item"),u=parseInt(i.dataset.index,10);isNaN(u)||T(u,u+1);return}});const B=t=>{const n=[...t].filter(C).filter(c=>g(c,s));if(!n.length){alert(`Invalid file type or format. Allowed: ${acceptHumanString||"Any"}`),A();return}if(!a)E([n[0]]);else{const c=new Set(o.map(y)),d=n.filter(i=>!c.has(y(i)));d.length>0?E([...o,...d]):A()}};r._assignFiles=B,e.addEventListener("change",()=>{if(z)return;const t=[...e.files||[]];if(t.length===0){o.length>0&&(o=[],F());return}R(t)?A():B(t)});const k=e.closest("form");k&&k.addEventListener("reset",()=>{o=[],F()}),["dragenter","dragover"].forEach(t=>{r.addEventListener(t,n=>{n.preventDefault(),n.stopPropagation(),r.classList.add("drag-over")})}),["dragleave","drop"].forEach(t=>{r.addEventListener(t,n=>{n.preventDefault(),n.stopPropagation(),r.classList.remove("drag-over")})}),r.addEventListener("drop",t=>{t.dataTransfer?.files?.length&&B(t.dataTransfer.files)})}),window._fileDropzonePasteBound||(window._fileDropzonePasteBound=!0,document.addEventListener("paste",e=>{const s=document.activeElement;if(s&&(s.tagName==="INPUT"&&s.type!=="file"||s.tagName==="TEXTAREA"||s.isContentEditable))return;const a=[...e.clipboardData?.items||[]].filter(f=>f.kind==="file").map(f=>f.getAsFile()).filter(Boolean);if(!a.length)return;const r=document.querySelector(".dropzone:focus-within")||document.querySelector(".dropzone:hover")||(document.querySelectorAll(".dropzone").length===1?document.querySelector(".dropzone"):null);r?._assignFiles&&(e.preventDefault(),r._assignFiles(a))}))})(),(()=>{const N=/^([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/;function x(){document.querySelectorAll('input[type="color"]:not([data-enhanced])').forEach(m=>{m.dataset.enhanced="true";const b=(m.value||"#000000").toUpperCase(),L=m.id?document.querySelector(`label[for="${m.id}"]`):m.closest("label"),g=document.createElement("div");g.className="input-colour-picker-group",g.innerHTML=`
        <div class="input-colour-picker-controls">
          <button class="btn input-colour-swatch-wrapper">
            <span class="input-colour-swatch-preview" style="background-color: ${b}"></span>
          </button>
          <div class="input-colour-hex-input-wrapper">
            <span class="input-colour-hex-prefix" aria-hidden="true">#</span>
            <input type="text" class="input-colour-hex-input" maxlength="6" spellcheck="false" autocomplete="off" value="${b.replace("#","")}" aria-invalid="false">
            <icon-mat class="input-colour-error-message material-symbols-rounded"   aria-live="polite">error</icon-mat>
          </div>
        </div>
      `;const C=g.querySelector(".input-colour-swatch-wrapper"),y=g.querySelector(".input-colour-swatch-preview"),v=g.querySelector(".input-colour-hex-input"),q=g.querySelector(".input-colour-error-message");m.classList.add("native-colour-input"),m.replaceWith(g),C.prepend(m),L&&(L.classList.add("input-colour-picker-label"),g.prepend(L));const S=h=>y.style.backgroundColor=h;m.addEventListener("input",h=>{const e=h.target.value.toUpperCase();document.activeElement!==v&&(v.value=e.replace("#","")),S(e),v.setAttribute("aria-invalid","false")}),v.addEventListener("input",()=>{let h=v.value.replace(/[^0-9A-Fa-f]/g,"").toUpperCase();if(v.value=h,N.test(h)){const s=`#${h.length===3?[...h].map(p=>p+p).join(""):h}`;m.value=s,S(s),v.setAttribute("aria-invalid","false"),m.dispatchEvent(new Event("input",{bubbles:!0}))}else v.setAttribute("aria-invalid","true")})})}document.readyState==="loading"?document.addEventListener("DOMContentLoaded",x):x()})();
