(()=>{const f=window.globalVar("docLang"),g=document.getElementById("download-platforms-box"),u=document.getElementById("github-fallback-btn"),v=document.getElementById("rel-latest"),p="gh_releases_cache",x=900*1e3,h=u.href.split("/").filter(Boolean)[3]||"archive",w=Date.now();let s={};try{s=JSON.parse(localStorage.getItem(p))||{}}catch{s={}}const b=s[h]||{},i=b.data,y=b.timestamp;function m(e){const o=e.assets||[];if(o.length===0)return;let _="",L=0;o.forEach(l=>{const n=l.name,r=n.toLowerCase(),t=l.browser_download_url,a=l.download_count||0;L+=a;let c="file_download",d="Asset";r.includes("android")?(c="os_android",d="Android"):r.includes("windows")?(c="os_windows",d="Windows"):r.includes("mac")&&(c="os_apple",d="macOS"),_+=`
                    <a href="${t}" target="_blank" rel="noopener" class="btn btn-secondary btn-fill btn-wide display-flex flex-horizontal" style="justify-content: space-between; align-items: center;">
                        <svg class="material-symbols-rounded" aria-hidden="true"><use href="/images/symbols_rounded.svg#${c}"></use></svg>
                        <div class="display-flex flex-vertical text-start flex-1"><span>${d}</span><span class="font-mono-thin file-name">${n}</span></div>
                        <span class="text-small display-flex flex-v-centre">
                            <svg class="material-symbols-rounded twemoji" aria-hidden="true"><use href="/images/symbols_rounded.svg#download"></use></svg>${a.toLocaleString()}
                        </span>
                    </a>
                `.trim()}),g.innerHTML=_;const $=e.published_at.split("T")[0],T=e.tag_name,A=l=>{const n=new Date(l);if(f==="en"){const r=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],t=n.getDate();let a="th";return t===1||t===21||t===31?a="st":t===2||t===22?a="nd":(t===3||t===23)&&(a="rd"),`${r[n.getMonth()]} ${t}<sup>${a}</sup>, ${n.getFullYear()}`}else return`${n.getFullYear()-1911} \u5E74 ${n.getMonth()+1} \u6708 ${n.getDate()} \u65E5`};v.innerHTML=`
                <time itemprop="dateModified" datetime="${$}" class="ctc-span">${A($)}</time>
                <span class="ctc-title">${f==="zh-tw"?"\u6700\u65B0\u7248\uFF0C":"Latest, "}<span class="font-mono-thin text-nowrap">${T}</span></span>
        `}i&&y&&w-y<x?m(i):fetch(u.href.replace("https://github.com/","https://api.github.com/repos/")).then(e=>{if(!e.ok)throw new Error("API Rate Limit or Repository Missing");return e.json()}).then(e=>{if(!Array.isArray(e)||e.length===0)return;const o=e[0];s[h]={timestamp:w,data:o},localStorage.setItem(p,JSON.stringify(s)),m(o)}).catch(e=>{console.log(e),i?m(i):g.remove()})})();
