const MAX_ATTEMPTS=6,TILES_COUNT=24;let STATION_SEARCH_INDEX={},target={index:0,name:"",line:""},revealed=[],attemptsLeft=6,attemptsUsed=0,answersArr=[],phase=1;const btnGuess=document.getElementById("btn-guess"),btnShare=document.getElementById("btn-share"),btnReplay=document.getElementById("btn-replay"),canvas=document.getElementById("stampCanvas"),ctx=canvas.getContext("2d"),toastEl=document.getElementById("toast"),snapshotArea=document.getElementById("snapshot-area"),tilesGrid=document.getElementById("tilesGrid"),linesArea=document.getElementById("linesArea"),candidatePanel=document.getElementById("candidatePanel"),searchInput=document.getElementById("searchInput"),stationGrid=document.getElementById("stationGrid"),capsuleMeter=document.getElementById("capsuleMeter");let capsules;const coord=[1,2,3,4].flatMap(e=>"ABCDEF".split("").map(t=>`(${t},${e})`));async function loadGameData(){try{const[e,t]=await Promise.all([fetch("data.json").then(s=>s.ok?s.json():null),fetch("/metro/data/station_aliases.json").then(s=>s.ok?s.json():null)]);e&&(dataset=e),t&&(STATION_SEARCH_INDEX=t)}catch(e){console.warn(e)}initRound()}function getLineKeyForIndex(e,t){let s=0;for(const[n,a]of Object.entries(t)){if(parseInt(e)<parseInt(a))return n;s=a}return Object.keys(t)[0]||"transfer"}function loadAndRenderStamp(){const e=window.devicePixelRatio||1,t=canvas.getBoundingClientRect();canvas.width=t.width*e,canvas.height=t.width*(2/3)*e,ctx.clearRect(0,0,canvas.width,canvas.height);const s=`stamps/${target.index+1}.png`,n=new Image;n.crossOrigin="Anonymous",n.src=s,n.onload=()=>{ctx.fillStyle="transparent",ctx.fillRect(0,0,canvas.width,canvas.height);const a=Math.min(canvas.width/n.width,canvas.height/n.height),o=n.width*a,l=n.height*a,i=(canvas.width-o)/2,c=(canvas.height-l)/2;ctx.drawImage(n,i,c,o,l)}}function initRound(){invalidateSnapshotCache();const e=Math.floor(Math.random()*dataset.stations.length);target.index=e,target.name=dataset.stations[e],target.line=getLineKeyForIndex(e,dataset.lines),revealed=Array(24).fill(!1),attemptsLeft=6,attemptsUsed=0,answersArr=new Array,phase=1,loadAndRenderStamp(),renderCandidateGrid(dataset.stations);const t=Math.floor(Math.random()*24);revealed[t]=!0,tilesGrid.innerHTML=Array.from({length:24}).map((s,n)=>`<div class="tile" id="tile-${n}"><span class="tile-num">${coord[n]}</span><span class="tile-tag" id="tag-${n}"></span></div>`).join(""),capsuleMeter.innerHTML=`
        <div class="capsule spent">
            <p class="text-small-title">\u96A8\u6A5F\u63ED\u9732</p>
            <p class="answer">${coord[t]}</p>
        </div>
        <div class="capsule">
            <p class="text-small-title">\u8DEF\u7DDA</p>
            <p id="ans-line" class="answer">---</p>
        </div>
        <div class="capsule">
            <p class="text-small-title">\u514D\u8CBB\u63ED\u9732</p>
            <p id="ans-free" class="answer">---</p>
        </div>`,capsuleMeter.innerHTML+=Array.from({length:6}).map((s,n)=>`
        <div class="capsule">
            <p class="text-small-title">\u6A5F\u6703 ${n+1}</p>
            <p id="ans-${n+1}" class="answer">---</p>
        </div>`).join(""),capsules=capsuleMeter.querySelectorAll(".capsule"),updateUI()}function log(e,t){const s=document.getElementById(t);s.textContent=e,s.parentElement.classList.add("spent")}function updateUI(){if(revealed.forEach((e,t)=>{const s=document.getElementById(`tile-${t}`);e?s.classList.add("revealed"):s.classList.remove("revealed")}),attemptsUsed>0&&log(answersArr.at(-1),`ans-${attemptsUsed}`),btnGuess.classList.toggle("display-none",!(phase!=3&&phase!=1.5)),btnShare.classList.toggle("display-none",phase!=3),btnReplay.classList.toggle("display-none",phase!=3),linesArea.parentElement.classList.toggle("display-none",phase!=1),tilesGrid.classList.toggle("locked",phase===1||phase===3),tilesGrid.classList.toggle("gameOver",phase===3),phase===1){const e=Object.keys(dataset.lines);linesArea.innerHTML=e.map(t=>`
            <button class="btn line-card" onclick="submitLineGuess('${t}')">
              <span>${t}</span>
            </button>
          `).join("")}else if(phase===1.5)for(let e=0;e<24;e++){const t=document.getElementById(`tag-${e}`);t.textContent="\u514D\u8CBB\u63ED\u9732",t.style.color="var(--success)"}else if(phase===2){for(let e=0;e<24;e++){const t=document.getElementById(`tag-${e}`);t.textContent="\u63ED\u9732",t.style.color="var(--accent)"}searchInput.value="",filterStations()}else if(phase===3)if(attemptsLeft<=0)capsuleMeter.innerHTML+=`
        <div class="capsule spent snapshot-hide">
            <p class="text-small-title">\u7B54\u6848</p>
            <p id="ans-result" class="answer">${target.name}</p>
        </div>`;else{const e=document.getElementById("ans-"+attemptsUsed);e.classList.add("snapshot-hide"),e.parentElement.innerHTML+='<p class="snapshot-only">\uFF08\u6B63\u89E3\uFF09</p>'}}function renderCandidateGrid(e){stationGrid.innerHTML=e.map(t=>`
        <button class="btn text-small" title="${t}" onclick="submitStationGuess('${t}')">${t}</button>
      `).join("")}function filterStations(){const e=searchInput.value.toLowerCase().trim();if(!e){renderCandidateGrid(dataset.stations);return}const t=window.Utils.convertKeyboardToJhuyin(e),s=dataset.stations.filter(n=>n.toLowerCase().includes(e)?!0:(STATION_SEARCH_INDEX[n]||[]).some(l=>{const i=l.toLowerCase();return i.includes(e)||i.includes(t)}));renderCandidateGrid(s)}function peelTile(e){const t=typeof e=="number"?e:parseInt(e,10);if(!revealed[t]){if(phase===1.5){revealed[t]=!0,log(coord[t],"ans-free"),showMessage("\u5DF2\u514D\u8CBB\u63ED\u9732"),phase=2,updateUI();return}phase===2&&(attemptsLeft--,attemptsUsed++,answersArr.push(coord[t]),revealed[t]=!0,attemptsLeft<=0?(showMessage("\u5DF2\u63ED\u9732\u4E26\u7528\u76E1\u6A5F\u6703"),handleLoss()):(showMessage(`\u5DF2\u63ED\u9732\uFF0C\u9918 ${attemptsLeft} \u6B21\u6A5F\u6703`),updateUI()))}}function submitStationGuess(e){if(!(phase===1.5||phase===3)){if(phase===1&&(phase=2),attemptsLeft--,attemptsUsed++,answersArr.push(e),e===target.name){phase=3,showMessage("\u606D\u559C\u7B54\u5C0D"),updateUI();let t="";attemptsUsed<=6/3?t="side":attemptsUsed<=6/3*2&&(t="top"),fireConfetti(t)}else attemptsLeft<=0?(showMessage("\u932F\u8AA4\uFF0C\u5DF2\u7528\u76E1\u6A5F\u6703"),handleLoss()):(showMessage(`\u932F\u8AA4\uFF0C\u9918 ${attemptsLeft} \u6B21\u6A5F\u6703`),updateUI());closeModal()}}function handleLoss(){phase=3,updateUI()}function submitLineGuess(e){if(phase!==1)return;e===target.line?(showMessage("\u8DEF\u7DDA\u6B63\u78BA\uFF0C\u7372\u5F97\u63ED\u9732\u6A5F\u6703"),phase=1.5):(showMessage(`\u8DEF\u7DDA\u932F\u8AA4\uFF0C\u5176\u5BE6\u662F${target.line}`),log("\u7121","ans-free"),phase=2),log(target.line,"ans-line"),closeModal(),updateUI()}function nextRound(){initRound()}loadGameData(),tilesGrid.addEventListener("click",e=>{const t=e.target.closest(".tile");if(!t)return;searchInput.value="";const s=parseInt(t.id.replace("tile-",""),10);peelTile(s)}),btnShare.addEventListener("click",()=>{generateSnapshotFeature({target:snapshotArea})});
